### ISSUE TITLE
TASK: Remove number literals and arithmetic operations from language core

### ISSUE THREAD

**Issue by grebaldi** [PackageFactory/PackageFactory.ComponentEngine#27]
Citing "The overall mission"  from https://github.com/PackageFactory/PackageFactory.ComponentEngine/discussions/26:

>  This language contains the bare minimum of constructs to allow for expression of rendered HTML code [...] and **only the most simple calculations** [...] to avoid the creation of components that attract logic

The existence of arithmetic operations will almost definitely lead to the attraction of logic in components. It is therefore better to remove them from the language core.

If legitimate use cases for arithmetic operations should arise in the future, it will still be possible to add them back. For now it'll be easier to develop the language without them.

**Comment by mhsdesign** [comment]
better this way, i also think we didnt had proper parsing for all valid arithmetic combinations:

```
-1 * 2 - 20 * -1
```

or did we?

**Comment by mhsdesign** [comment]
haha i thought so ^^ i noticed as this doesnt work with my parsica parser (the parsica parser is just not ripe for binary expressions ^^)

**Comment by grebaldi** [comment]
We must preserve NumberLiterals, because of Enum values. But I think it'd be fair to limit those to (signed) integers.

**Comment by grebaldi** [comment]
Hmm...

> We must preserve NumberLiterals, because of Enum values. But I think it'd be fair to limit those to (signed) integers.

The more I come to think of it, the more I'm convinced numbers should actually go entirely. With that, numeric comparators would become obsolete as well.

I think, it'd be worthwhile to remove both and see, if any use case comes up that forces us to add them back.

**Comment by mhsdesign** [comment]
Hmm maybe @nezaniel can think of a usecase for numbers in the presentation… I mean removing them would limit component APIs to string and bool as primitives.

**Comment by grebaldi** [comment]
Okay, I think I'll leave numbers for now, so the engine can move forward. 

I'd like to finish https://github.com/PackageFactory/PackageFactory.ComponentEngine/pull/29 before moving on with https://github.com/PackageFactory/PackageFactory.ComponentEngine/issues/30.
